name: Firebase continuos deployment

on:
  push:
    branches:
      - main

jobs:
  deploy_to_web: # This job only runs when there is a prerelease
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@master

      - name: "Setup Node"
        uses: actions/setup-node@master
        with:
          node-version: 20

      - name: "Create env file to build"
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: "Installing dependencies"
        run: npm ci

      - name: "Installing Firebase tools" # This package is not included on package.json
        run: npm install -g firebase-tools

      - name: "Building app"
        run: npm run build

      - name: "Deploying to Firebase"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy -P ${{ secrets.FIREBASE_PROJECT_ID }}
